### ISSUE TITLE
Assign Ray to all pull requests moving forward to be approved.

### ISSUE THREAD

**Issue by hc-rabid** [khalidkanaan/devops-students#32]
@khalidkanaan - since you own this repo, I'll task you with assigning the team to the roles necessary to carry out this workflow. I may need write privilege and the rest of the team might fall under triage. Let me know if you want to look into this together or if you will handle it.

**Comment by khalidkanaan** [comment]
I should be able to handle things with the other students, but if I have any questions then I'll consult you about it. I have sent you an invitation to the repo and we will add you to our PRs as a reviewer moving forward.
