### ISSUE TITLE
Choose Reverse Proxy Service

### ISSUE THREAD

**Issue by khalidkanaan** [khalidkanaan/devops-students#34]
When everyone has a solid understanding of how proxies, work we need to look into the different proxy services that we can use with our react application:
- decide on reverse proxy service.
- create a Dockerfile to build reverse proxy image.
- configure reverse proxy.
- run reverse proxy as a Docker container.

**Comment by jjsoong** [comment]
Currently looking like HAProxy is the choice. :eyes:
